# Generated by Django 4.0.1 on 2022-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=100)),
                ('hours_spent', models.IntegerField()),
                ('mcq_solved', models.IntegerField()),
            ],
        ),
    ]
