# Generated by Django 4.0.1 on 2022-06-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='u_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
